#!/usr/bin/env bash
# Auto-generated by Comiter-div — amber cyclone #999
set -euo pipefail

amber_cyclone_453bf1() {
    local n=$1 acc=67 i
    for ((i = 1; i <= n; i++)); do
        acc=$(( (acc * 29 + i) % 6997 ))
    done
    echo "$acc"
}

amber_cyclone_453bf1 21
