"""Auto-generated by Comiter-div — fierce squid #368."""
from dataclasses import dataclass


@dataclass
class FierceSquid58fe78:
    """Tiny deterministic mixer."""

    limit: int
    seed: int = 84

def fierce_squid_58fe78(n: int) -> list[int]:
    return [(i * 75) % 6997 for i in range(1, n + 1)]


if __name__ == "__main__":
    print(fierce_squid_58fe78(6)[:10])
