# Auto-generated by Comiter-div — savage cyclone #173
def savage_cyclone_06448f(limit)
  (20..limit).each_with_object([]) do |i, out|
    out << (i * 74) % 769 if (i % 4).zero?
  end
end

puts savage_cyclone_06448f(30).first(10).inspect
